# Generated by Django 5.2.7 on 2025-10-29 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lot_number', models.CharField(max_length=50)),
                ('payment_scheme', models.CharField(choices=[('Full Payment', 'Full Payment'), ('Installments', 'Installments')], max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='BurialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField()),
                ('date_of_burial', models.DateField()),
                ('section', models.CharField(max_length=50)),
                ('lot_number', models.CharField(max_length=50)),
                ('burial_type', models.CharField(choices=[('Regular', 'Regular'), ('Private', 'Private')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burial_records', to='app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('paid', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='app.client')),
            ],
        ),
    ]
