# Generated by Django 5.2.7 on 2025-10-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
