# Generated by Django 5.2.7 on 2025-10-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_client_address_client_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burialrecord',
            name='burial_type',
        ),
        migrations.RemoveField(
            model_name='burialrecord',
            name='lot_number',
        ),
        migrations.RemoveField(
            model_name='burialrecord',
            name='section',
        ),
    ]
